name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup GHC
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'
      
      - name: Build
        run: |
          make
